# Generated by Django 5.0.14 on 2025-06-16 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Product name"
                    ),
                ),
                (
                    "part_number",
                    models.CharField(unique=True, verbose_name="Part number"),
                ),
                ("brand", models.CharField(verbose_name="Brand name")),
                (
                    "package_count",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Can not be less than 1 units!"
                            )
                        ],
                        verbose_name="Package units count",
                    ),
                ),
                (
                    "volume",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Can not be less than 1 litres!"
                            )
                        ],
                        verbose_name="Voulume in litres",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=240, verbose_name="Product description"
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        max_length=240, verbose_name="Product specification"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/product_image/",
                        verbose_name="Product image",
                    ),
                ),
                (
                    "specification_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/product_specification_file/",
                        verbose_name="Product specification file",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время размещения"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время обновления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["brand"],
                "indexes": [
                    models.Index(fields=["id"], name="catalog_pro_id_7100fc_idx"),
                    models.Index(fields=["name"], name="catalog_pro_name_f603c0_idx"),
                    models.Index(
                        fields=["-created"], name="catalog_pro_created_b92f5e_idx"
                    ),
                ],
            },
        ),
    ]
