# Generated by Django 5.0.14 on 2025-06-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="id",
        ),
        migrations.AlterField(
            model_name="product",
            name="part_number",
            field=models.CharField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Part number",
            ),
        ),
    ]
