# Generated by Django 5.0.14 on 2025-06-18 07:33

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimages",
            name="images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=catalog.models.product_image_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "gif"]
                    )
                ],
                verbose_name="Product images",
            ),
        ),
    ]
