# Generated by Django 5.0.14 on 2025-06-18 08:31

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_productimages_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimages",
            options={"verbose_name": "Product image"},
        ),
        migrations.RemoveField(
            model_name="productimages",
            name="images",
        ),
        migrations.AddField(
            model_name="productimages",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=catalog.models.product_image_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "gif"]
                    )
                ],
                verbose_name="Product image",
            ),
        ),
    ]
