# Generated by Django 5.0.14 on 2025-06-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_price_per_unit_product_price_per_box"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalog",
            name="supplier",
        ),
    ]
