# Generated by Django 5.0.14 on 2025-06-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_remove_catalog_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="arrival_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Estimated arrival date"
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="updated_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date of count and transit updated"
            ),
        ),
    ]
