# Generated by Django 5.0.14 on 2025-06-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_catalog_arrival_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="specification",
            field=models.CharField(
                default="nan", max_length=240, verbose_name="Product specification"
            ),
            preserve_default=False,
        ),
    ]
