# Generated by Django 5.0.14 on 2025-06-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_catalog_specification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="arrival_date",
            field=models.CharField(
                blank=True, null=True, verbose_name="Estimated arrival date"
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="updated_date",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="Date of count and transit updated",
            ),
        ),
    ]
