# Generated by Django 5.0.14 on 2025-06-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(verbose_name="Order delivery date"),
        ),
    ]
