# Generated by Django 5.0.14 on 2025-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_delivery_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Order comment"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Order delivery date"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, null=True, unique=True, verbose_name="Order number"
            ),
        ),
    ]
