# Generated by Django 5.0.14 on 2025-06-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_comment_alter_order_delivery_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="rs_code",
            new_name="dealer",
        ),
    ]
