# Generated by Django 5.0.14 on 2025-06-12 20:39

import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealer",
            name="inn",
            field=models.BigIntegerField(
                validators=[users.validators.validate_inn], verbose_name="Dealer INN"
            ),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="rs_code",
            field=models.CharField(
                validators=[users.validators.validate_dealer_code],
                verbose_name="Dealer RS code",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="inn",
            field=models.BigIntegerField(
                validators=[users.validators.validate_inn], verbose_name="Supplier INN"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rs_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer_users",
                to="users.dealer",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_users",
                to="users.supplier",
            ),
        ),
    ]
