# Generated by Django 5.0.14 on 2025-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_supplier_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="legal_name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Unique supplier legal name"
            ),
        ),
    ]
