# Generated by Django 5.0.14 on 2025-06-20 06:58

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_supplier_legal_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dealer",
            name="phone",
        ),
        migrations.AddField(
            model_name="dealer",
            name="address",
            field=models.CharField(
                default=0, max_length=240, verbose_name="Dealer address"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dealer",
            name="city",
            field=models.CharField(
                default=0, max_length=50, verbose_name="Dealer city name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dealer",
            name="legal_address",
            field=models.CharField(
                default=0, max_length=240, verbose_name="Dealer legal address"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=0, max_length=128, region="RU"
            ),
            preserve_default=False,
        ),
    ]
