# Generated by Django 5.0.14 on 2025-06-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_dealer_phone_dealer_address_dealer_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rs_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dealer_users",
                to="users.dealer",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_users",
                to="users.supplier",
            ),
        ),
    ]
