# Generated by Django 5.0.14 on 2025-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_rs_code_alter_user_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_dealer_admin",
            field=models.BooleanField(default=False),
        ),
    ]
