# Generated by Django 5.0.14 on 2025-07-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_is_dealer_admin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dealer",
            options={
                "ordering": ["id"],
                "verbose_name": "Dealer",
                "verbose_name_plural": "Dealers",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["id"],
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
    ]
