# Generated by Django 5.0.14 on 2025-07-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_dealer_options_alter_supplier_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="delivery_time",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Delivery time to dealer"
            ),
        ),
        migrations.AddField(
            model_name="dealer",
            name="transport_size_limitation",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Transport size limitation",
            ),
        ),
    ]
